### ISSUE TITLE
Crate does not compile on 1.56

### ISSUE THREAD

**Issue by jorgecarleitao** [rust-lang/packed_simd#328]
```bash
error[E0557]: feature has been removed
   --> /home/azureuser/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.5/src/lib.rs:215:5
    |
215 |     const_generics,
    |     ^^^^^^^^^^^^^^ feature has been removed
```

> cargo 1.56.0-nightly (f559c109c 2021-08-26)

**Comment by JohnTitor** [comment]
The below is `cargo tree` output:

```
phf v0.10.0
├── phf_macros v0.10.0
│   ├── phf_generator v0.10.0
│   │   ├── phf_shared v0.10.0
│   │   │   ├── siphasher v0.3.6
│   │   │   ├── uncased v0.9.6
│   │   │   │   [build-dependencies]
│   │   │   │   └── version_check v0.9.3
│   │   │   └── unicase v2.6.0
│   │   │       [build-dependencies]
│   │   │       └── version_check v0.9.3
│   │   └── rand v0.8.4
│   │       ├── libc v0.2.101
│   │       ├── rand_chacha v0.3.1
│   │       │   ├── ppv-lite86 v0.2.10
│   │       │   └── rand_core v0.6.3
│   │       │       └── getrandom v0.2.3
│   │       │           ├── cfg-if v1.0.0
│   │       │           └── libc v0.2.101
│   │       └── rand_core v0.6.3 (*)
│   │   [dev-dependencies]
│   │   └── criterion v0.3.4
│   │       ├── atty v0.2.14
│   │       │   └── libc v0.2.101
│   │       ├── cast v0.2.7
│   │       │   [build-dependencies]
│   │       │   └── rustc_version v0.4.0
│   │       │       └── semver v1.0.4
│   │       ├── clap v2.33.3
│   │       │   ├── bitflags v1.3.2
│   │       │   ├── textwrap v0.11.0
│   │       │   │   └── unicode-width v0.1.8
│   │       │   └── unicode-width v0.1.8
│   │       ├── criterion-plot v0.4.4
│   │       │   ├── cast v0.2.7 (*)
│   │       │   └── itertools v0.10.1
│   │       │       └── either v1.6.1
│   │       ├── csv v1.1.6
│   │       │   ├── bstr v0.2.16
│   │       │   │   ├── lazy_static v1.4.0
│   │       │   │   ├── memchr v2.4.1
│   │       │   │   ├── regex-automata v0.1.10
│   │       │   │   └── serde v1.0.130
│   │       │   │       └── serde_derive v1.0.130
│   │       │   │           ├── proc-macro2 v1.0.29
│   │       │   │           │   └── unicode-xid v0.2.2
│   │       │   │           ├── quote v1.0.9
│   │       │   │           │   └── proc-macro2 v1.0.29 (*)
│   │       │   │           └── syn v1.0.75
│   │       │   │               ├── proc-macro2 v1.0.29 (*)
│   │       │   │               ├── quote v1.0.9 (*)
│   │       │   │               └── unicode-xid v0.2.2
│   │       │   ├── csv-core v0.1.10
│   │       │   │   └── memchr v2.4.1
│   │       │   ├── itoa v0.4.8
│   │       │   ├── ryu v1.0.5
│   │       │   └── serde v1.0.130 (*)
│   │       ├── itertools v0.10.1 (*)
│   │       ├── lazy_static v1.4.0
│   │       ├── num-traits v0.2.14
│   │       │   [build-dependencies]
│   │       │   └── autocfg v1.0.1
│   │       ├── oorandom v11.1.3
│   │       ├── plotters v0.3.1
│   │       │   ├── num-traits v0.2.14 (*)
│   │       │   ├── plotters-backend v0.3.2
│   │       │   └── plotters-svg v0.3.1
│   │       │       └── plotters-backend v0.3.2
│   │       ├── rayon v1.5.1
│   │       │   ├── crossbeam-deque v0.8.1
│   │       │   │   ├── cfg-if v1.0.0
│   │       │   │   ├── crossbeam-epoch v0.9.5
│   │       │   │   │   ├── cfg-if v1.0.0
│   │       │   │   │   ├── crossbeam-utils v0.8.5
│   │       │   │   │   │   ├── cfg-if v1.0.0
│   │       │   │   │   │   └── lazy_static v1.4.0
│   │       │   │   │   ├── lazy_static v1.4.0
│   │       │   │   │   ├── memoffset v0.6.4
│   │       │   │   │   │   [build-dependencies]
│   │       │   │   │   │   └── autocfg v1.0.1
│   │       │   │   │   └── scopeguard v1.1.0
│   │       │   │   └── crossbeam-utils v0.8.5 (*)
│   │       │   ├── either v1.6.1
│   │       │   └── rayon-core v1.9.1
│   │       │       ├── crossbeam-channel v0.5.1
│   │       │       │   ├── cfg-if v1.0.0
│   │       │       │   └── crossbeam-utils v0.8.5 (*)
│   │       │       ├── crossbeam-deque v0.8.1 (*)
│   │       │       ├── crossbeam-utils v0.8.5 (*)
│   │       │       ├── lazy_static v1.4.0
│   │       │       └── num_cpus v1.13.0
│   │       │           └── libc v0.2.101
│   │       │   [build-dependencies]
│   │       │   └── autocfg v1.0.1
│   │       ├── regex v1.5.4
│   │       │   └── regex-syntax v0.6.25
│   │       ├── serde v1.0.130 (*)
│   │       ├── serde_cbor v0.11.2
│   │       │   ├── half v1.7.1
│   │       │   └── serde v1.0.130 (*)
│   │       ├── serde_derive v1.0.130 (*)
│   │       ├── serde_json v1.0.67
│   │       │   ├── itoa v0.4.8
│   │       │   ├── ryu v1.0.5
│   │       │   └── serde v1.0.130 (*)
│   │       ├── tinytemplate v1.2.1
│   │       │   ├── serde v1.0.130 (*)
│   │       │   └── serde_json v1.0.67 (*)
│   │       └── walkdir v2.3.2
│   │           └── same-file v1.0.6
│   ├── phf_shared v0.10.0 (*)
│   ├── proc-macro-hack v0.5.19
│   ├── proc-macro2 v1.0.29 (*)
│   ├── quote v1.0.9 (*)
│   └── syn v1.0.75 (*)
│   [dev-dependencies]
│   ├── phf v0.10.0 (*)
│   ├── trybuild v1.0.45
│   │   ├── glob v0.3.0
│   │   ├── lazy_static v1.4.0
│   │   ├── serde v1.0.130 (*)
│   │   ├── serde_json v1.0.67 (*)
│   │   ├── termcolor v1.1.2
│   │   └── toml v0.5.8
│   │       └── serde v1.0.130 (*)
│   └── unicase v2.6.0 (*)
├── phf_shared v0.10.0 (*)
└── proc-macro-hack v0.5.19
```

It doesn't contain `packed_simd_2` package, please double-check your dependency tree and update it if it's outdated.

**Comment by jorgecarleitao** [comment]
Not sure why we are looking at `phf`; the crate I am compiling is `arrow2`, with feature `simd`, which does depend on `packed_simd2`.

See [this log](https://github.com/jorgecarleitao/arrow2/pull/363/checks?check_run_id=3489648760), which fails with the latest nightly, vs [this log](https://github.com/jorgecarleitao/arrow2/pull/364/checks?check_run_id=3490051244) which was produced [after pinning](https://github.com/jorgecarleitao/arrow2/pull/364/files) nightly.

**Comment by JohnTitor** [comment]
Aha! I completely misunderstood where this issue is on. Sorry about that!
Yes, packed_simd needs an update for https://github.com/rust-lang/rust/pull/88369.

**Comment by krojew** [comment]
Ran into this too.
