### PR TITLE
Rename `const_generics` feature gate to `adt_const_params`

### LINKED ISSUE #328: Crate does not compile on 1.56
```bash
error[E0557]: feature has been removed
   --> /home/azureuser/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.5/src/lib.rs:215:5
    |
215 |     const_generics,
    |     ^^^^^^^^^^^^^^ feature has been removed
```

> cargo 1.56.0-nightly (f559c109c 2021-08-26)

### PR DESCRIPTION
**Pull request by JohnTitor**
Fixes #328

### CODE REVIEW

**Comment by JohnTitor** [comment]
Hmm, it seems Travis CI for this repo has been turned off: https://app.travis-ci.com/github/rust-lang/packed_simd
It's time to migrate to GHA :)

**Comment by krojew** [comment]
Any chance for merging this? 😉

**Comment by TheIronBorn** [comment]
If packed_simd is failing in an upstream crate or any other dependency you can't change, add this to your `Cargo.toml`
```toml
[patch.crates-io]
packed_simd = { git = "https://github.com/JohnTitor/packed_simd", branch = "rename-const-generics-feature-gate", package = "packed_simd_2" }

**Comment by calebzulawski** [comment]
This project is effectively retired, so I'm not sure what we want to do about CI.  @workingjubilee?

**Comment by workingjubilee** [comment]
Once more for old time's sake, I suppose.

**Comment by workingjubilee** [comment]
Published this version as a point release: 0.3.6
Yes, Travis CI has broken for basically everything.
I will review a PR that changes it over.
